# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'My website'
description: 'This is my new website'
permalink: pretty
logo: "https://southhamssociety.org/wp-content/uploads/2021/03/Final-SHS-60th-logo-website.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Latest News
    output: true
    description: 
    feature_text: |
      
    feature_image: 

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
